name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt update
    - name: apt install libsystemd-dev
      run: sudo apt install -y --no-install-recommends libsystemd-dev
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
          name: binoutput
          path: ./target/release/leftw*
   
